import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'
import Image from  'next/image';
import deved from '../public/dev-ed-wave.png';
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Salami Emmanuel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-teal-600'>TOBILOBA</h1>
            <ul className=' flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl dark:text-white'/></li>
              <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'> Salami Emmanuel</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Developer and designer.</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-green-100'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet necessitatibus molestias voluptates alias dolores placeat, debitis quo provident nobis recusandae ea iure earum sequi tenetur distinctio est dignissimos eaque eos!
            </p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillInstagram/>
          </div>
          <div className='  relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} fill="true" style={{objectFit:'cover'}}/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>
              Sevices I offer
            </h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-green-100'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta assumenda quasi quo odit facilis ratione ducimus vero adipisci possimus, a esse provident! Est expedita consequatur velit recusandae, vitae commodi maxime?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempore aspernatur atque amet, sapiente sint ea officiis vel consectetur consequatur dolorum molestiae, magnam culpa nulla! Veritatis, dicta facilis! Magnam, provident.</p>
          </div>

          <div className=' lg:flex gap-10'>
            <div className='  text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} className=' mx-auto'/>
              <h3 className=' text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className=' py-2 dark:text-white'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio, optio iusto, magni error sequi reprehenderit dicta perspiciatis porro iste laborum, deleniti eligendi dolorem necessitatibus distinctio dolor commodi inventore eum quidem.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools i use</h4>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Figma</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Photoshop</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Illustrator</p>
            </div>

            <div className='  text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} className=' mx-auto'/>
              <h3 className=' text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className=' py-2 dark:text-white'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio, optio iusto, magni error sequi reprehenderit dicta perspiciatis porro iste laborum, deleniti eligendi dolorem necessitatibus distinctio dolor commodi inventore eum quidem.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools i use</h4>
              <p className=' text-gray-800 py-1 dark:text-green-100'>HTML</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>React</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Illustrator</p>
            </div>

            <div className='  text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100} className=' mx-auto'/>
              <h3 className=' text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className=' py-2 dark:text-white'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio, optio iusto, magni error sequi reprehenderit dicta perspiciatis porro iste laborum, deleniti eligendi dolorem necessitatibus distinctio dolor commodi inventore eum quidem.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools i use</h4>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Figma</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Photoshop</p>
              <p className=' text-gray-800 py-1 dark:text-green-100'>Illustrator</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>Portfoilo</h3>
            <p className=' text-md py-2 leading-8 text-gray-800  dark:text-green-100'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus, quas ab cum autem tenetur architecto at est voluptatem eum quae laboriosam ducimus magni enim assumenda sunt mollitia reiciendis doloremque natus.</p>
            <p className=' text-md py-2 leading-8 text-gray-800  dark:text-green-100'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore numquam, fuga reiciendis quae, qui impedit doloremque eveniet ratione tenetur obcaecati eum enim possimus adipisci est quod consequatur incidunt illo soluta?</p>
          </div>
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className=' basis-1/3 flex-1'>
            <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
          </div>
          </div>
         
        </section>
      </main>
    </div>
  )
}
